# Generated by Django 3.0.8 on 2020-08-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('time_open', models.TimeField(help_text='время в формате  00:00', verbose_name='Время открытия')),
                ('time_close', models.TimeField(help_text='время в формате  00:00', verbose_name='Время закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['created_at'],
            },
        ),
    ]
