# Generated by Django 3.0.8 on 2020-08-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='street.Street', verbose_name='Улица'),
        ),
    ]
